### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zhangquanchen** [niladridutt/Diffusion-3D-Features#4]
Hi, it seems that url http://tosca.cs.technion.ac.il/data/toscahires-mat.zip is not available.
And I notice that you are using another way to load it by "tosca_data_path = "datasets/tosca/Meshes""
So would you mind providing me with your tosca dataset? Thanks!

**Comment by niladridutt** [comment]
You will be able to find TOSCA and SHREC'07 datasets from here- http://www.vovakim.com/projects/CorrsBlended/SurfCorr2.0.benchmarks.bins.zip
The official TOSCA website does not seem to work at the moment

**Comment by zhangquanchen** [comment]
Thank you so much for the url you providing!!! I have searched for a long time because of the unknown closing of official TOSCA website. It is important for me. Thanks for your help!
