### ISSUE TITLE
No runwayml/stable-diffusion-v1-5 anymore

### ISSUE THREAD

**Issue by Cao-Cong0** [niladridutt/Diffusion-3D-Features#8]
OSError: runwayml/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

**Comment by niladridutt** [comment]
Hi!
You're correct; looks like Runway took down their models. 
You can use this identifier as an alternative `benjamin-paine/stable-diffusion-v1-5` from https://huggingface.co/benjamin-paine/stable-diffusion-v1-5. It's the same model which has been re-uploaded as per the previous license
